### ISSUE TITLE
SQL Error with [SET TRANSACTION]

### ISSUE THREAD

**Issue by Andymic** [schotime/NPoco#182]
Hi,

When doing a db.fetch<MyModel>(Sql), if the sql  contains either one or both of these:
-SET NOCOUNT ON
-SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

Npoco throws an error "Invalid object name 'MyModel' ". According to Microsoft's documentation they are valid statements in SQL Server 204.  Is there a way around that? 

*Also the error is kind of misleading because the issue is not related to the Model. 

Thanks

**Comment by dheijl** [comment]
Perhaps Fetch() can't parse that kind of statement. You could use Execute() for these and do the actual fetching with  Fetch() ?

**Comment by warrenrumak** [comment]
NPoco is expecting you to provide either a complete SELECT query or a WHERE statement, so that it can parse your SQL for things like parameterization and property mapping.  

If you don't start the statement with SELECT, NPoco writes the SELECT portion for you, then appends your query text.  You can verify this with SQL Profiler; you'll see something like "SELECT [One], [Two], [Three] FROM [MyModel] SET NOCOUNT ON" (etc.)

To override this behaviour, start the query string with a semicolon.

**Comment by Andymic** [comment]
@dheijl  thanks for the suggestion but db.Execute would not quite get the job done as I am expecting a result set.

@warrenrumak  Great. I will try that and update. Thanks!

**Comment by schotime** [comment]
@warrenrumak's answer regarding starting with a ';' should solve it

**Comment by clagoos** [comment]
It's important to mention that ; is required to be the first character in query, so query typed in C# in this way won't work:
```
//not working
const string query = @"
    ;here
    goes
    my
    query";
```
You have to write it that way (with semicolon ; right after opening " sign):
```
//this works
const string query = @";
    here
    goes
    my
    query";
```
