### ISSUE TITLE
Column lookup key does not match for nested objects

### ISSUE THREAD

**Issue by schotime** [schotime/NPoco#236]
Here is what i noticed.

Album mapping
```
public class AlbumMappings : Mappings<Album>
{
  AlbumMappings()
  {
    Columns( x=>
    {
        // column is generated with key 'Artist'.
        x.Column(c => c.Artist).Reference(f => f.ArtistId, ReferenceType.OneToOne).Result(); 
    }, true); // use explicit column definition
  }
}
```

FluentMappingPocoDataBuilder
```
protected override ColumnInfo GetColumnInfo(MemberInfo mi, MemberInfo[] memberInfos)
{
  // key is 'Artist__ArtistId'
  var key = PocoColumn.GenerateKey(memberInfos.Concat(new[] { mi }));
  bool explicitColumns = typeConfig.ExplicitColumns ?? false;
  // well, column not defined ??
  var isColumnDefined = typeConfig.ColumnConfiguration.ContainsKey(key);
  ...
  
  // resulting column being ignored for further column mapping aliasing
  if (explicitColumns && !isColumnDefined)
    columnInfo.IgnoreColumn = true;
}
```
Those problems does not occurs using Attributes, only with FluentMappings. Any clean work around for this problems?

**Comment by schotime** [comment]
@dwirawan Can you explain why this is an issue? and what problem you are getting because of it?

**Comment by dwirawan** [comment]
sorry for catching up late, here is the full snippet to give the idea.

Album class
```
public class Album
{
    public int AlbumId { get; set; }
    public string Title { get; set; }
    public int ArtistId { get; set; }
    public Artist Artist { get; set; }
}
```
Album class with attributes
```
[TableName("albums")]
[PrimaryKey("albumid")]
[ExplicitColumns]
public class Album
{
    [Column("albumid")]
    public int AlbumId { get; set; }
    [Column("title")]
    public string Title { get; set; }
    [Column("artistid")]
    public int ArtistId { get; set; }
    [ResultColumn]
    [Reference(ReferenceType.OneToOne, ColumnName = "artistid", ReferenceMemberName = "ArtistId")]
    public Artist Artist { get; set; }
}
```
Artist class
```
public class Artist
{
    public int ArtistId { get; set; }
    public string Name { get; set; }
    public List<Album> Albums { get; set; }
}
```
Artist class with attributes
```
[TableName("artists")]
[PrimaryKey("artistid")]
[ExplicitColumns]
public class Artist
{
    [Column("artistid")]
    public int ArtistId { get; set; }
    [Column("name")]
    public string Name { get; set; }
    [ResultColumn]
    [Reference(ReferenceType.Many, ColumnName = "artistid", ReferenceMemberName = "ArtistId")]
    public List<Album> Albums { get; set; }
}
```
Mapping class
```
public class EntityMappings : Mappings
{
    public EntityMappings()
    {
        For<Artist>()
            .TableName("artist")
            .PrimaryKey("artistid")
            .Columns(x => 
            {
                x.Column(c => c.ArtistId).WithName("artistid");
                x.Column(c => c.Name).WithName("name");
                // actually i don't know how to configure many reference to List<Album> ? missing something?
            }, true);
        For<Album>()
            .TableName("albums")
            .PrimaryKey("albumid")
            .Columns(x => 
            {
                x.Column(c => c.AlbumId).WithName("albumid");
                x.Column(c => c.Title).WithName("title");
                x.Column(c => c.ArtistId).WithName("artistid");
                x.Column(c => c.Artist).Reference(r => r.ArtistId, ReferenceType.OneToOne);
            }, true);
    }
}
```
Database factory snippet
```
private static readonly DatabaseFactory _factory = DatabaseFactory.Config(x =>
{
    x.UsingDatabase(() => new Database("csname"));
    x.WithFluentConfig(FluentMappingConfiguration.Configure(new EntityMappings()));
});
```
Test snippet
```
using (var db = factory.GetDatabase())
{
  var r = db.Fetch<Album>("select a.*,r.* from albums a left join artitst r on a.artistid=r.artistid");
}
```
So here is the problem.
Fetch result does not contain the nested ``Artist`` object as expected (null). 
From my investigation during debugging session in ``PocoDataBuilder.Build()``, resulted ``PocoData.Members`` for ``Album`` class does not contains ``PocoMemberChildren`` for member ``Artist``, therefore it can't build map plans correctly. Continuing from my finding above ``_memberPlans`` returned from ``Attribute`` and ``FluentMapping`` behave differently, due to mismatch above, ``FluentMapping`` decide to ignored the child member of the nested object.
My idea is to create method to directly specify reference in ``ColumnConfigurationBuilder``, so instead of using ``ColumnConfigurationBuilder.Column().Reference()`` to specify reference, it can directly call ``ColumnConfigurationBuilder.ReferenceColumn()`` so that _columndefinitions can directly build column key for nested object. Is that possible?

**Comment by schotime** [comment]
Give the latest or beta7 a go ;)

**Comment by dwirawan** [comment]
@schotime i will give it a try, can you commit the changes? since i don't find new code in dev3.1, for now i will evaluate from nuget. thanks, gonna report to you soon :)

**Comment by dwirawan** [comment]
@schotime well, i still having above issue as well with beta7, since latest code is not available, i cant figure out what really happening under the hood.

**Comment by schotime** [comment]
Pushed.

**Comment by dwirawan** [comment]
thanks. gonna check it

**Comment by dwirawan** [comment]
hi @schotime, already checked the code, and it still experiencing above issue, i think the problem lies on ``FluentMappingPocoBuilder.GetColumnInfo`` for childmember of a nested object, ``GetColumnInfo`` assume only for direct member but not for child's member, sorry i might be misleading about the lookup key mismatch, but here is my silly ideas:
1. Refactor ``GetColumnInfo`` so it can distinguish between direct member and child's member (checking against  in ``TypeDefinition.ColumnConfiguration``), or
2. TypeDefinition.ColumnConfiguration should build nested object members.

What do you think?

**Comment by schotime** [comment]
This examples works for me. 
The only difference I can see is that Artist should have its column set.

```
x.Column(c => c.Artist).WithName("artistid").Reference(r => r.ArtistId, ReferenceType.OneToOne);
```

I will commit my example that shows it working.

**Comment by schotime** [comment]
I think I have found what you mean. 
I am using the convention scanning. That is the difference. It does the recursion. Back to the drawing board. Number 2 is the way to go.

**Comment by schotime** [comment]
Ok. Latest commit to dev3.1 should solve it. Was pretty easy in the end. Not sure why it was the way it was in the end. Have added the scenario above in IncludesWithLinqProvider with Test3/Test4.

**Comment by dwirawan** [comment]
@schotime just check it, and it works as expected, thanks :+1:

**Comment by schotime** [comment]
Awesome!
