### ISSUE TITLE
Creating Custom Ignore attribute only for Update methods?

### ISSUE THREAD

**Issue by evaldas-raisutis** [schotime/NPoco#305]
I would like to be able to create a custom attribute, such as [IngoreUpdate], which work much like [Ignore], but only when updating a model. Is this possible? 

Best regards,
Evaldas

**Comment by slobber** [comment]
sure, i think you need to inherite [Database](https://github.com/schotime/NPoco/blob/master/src/NPoco/Database.cs) class, then override OnUpdating method to deal with your custom attribute. 
Going one step further, you can create a memory cache to save your ignore attributes data of different entities after update first time in OnUpdating method.
But, I am more inclined this feature is not npoco should be concerned, because maybe someone else need other attribute like IgnoreInsert :p
