### ISSUE TITLE
Incorrect exception being raised with SQLite

### ISSUE THREAD

**Issue by makingbloke** [schotime/NPoco#317]
If I open a SQLite database using one of the standard constructors like this:

`this.db = new NPoco.Database(connectionStringBuilder.ConnectionString, DatabaseType.SQLite);`

and the database specified in the DataSource does not exist then instead of getting the expected System.Data.SQLite.SQLiteException I get a System.Reflection.TargetInvocationException with the SQLite exception held in the InnerException. Is this correct? I would have thought in cases like this NPOCO should have raised the database exception.

Cheers,

Edit 25/8: I downloaded the current master and tried with this. I get the same issue.

**Comment by schotime** [comment]
Sorry, but I will need more information about the exception.
Its likely because it is using the DbFactoryProviders to instantiate the connection. We are not catching the exception in NPoco, but if you can send us more info then we can look further. Even a sample console application showing the problem.

**Comment by makingbloke** [comment]
<red face>Sorry! My fault entirely, I setup a test harness and it raised the correct exception. After a lot of debugging it turns out I'm opening the database in a service  which is being injected by MVVM Light's ViewModelLocator class. When the caller receives the exception it looks like MVVM Light is wrapping it in a TargetInvocationException.</red face> Sorry again :)
