### ISSUE TITLE
Improve PostgreSQL array support

### ISSUE THREAD

**Issue by nathan-alden-sr** [schotime/NPoco#326]
I am running NPoco 3.4.3 with Npgsql 3.1.7.

It seems that NPoco does not support PostgreSQL arrays. Whenever I specify `string[]` or `IEnumerable<string>` as a parameter (e.g., in `Sql.Builder`), the parameter value is converted to `string` and I get errors like this:

```
{"42804: column \"foo\" is of type text[] but expression is of type text"}
```

To work around this issue, I had to create this extension method:

```
public static NpgsqlParameter ToArrayNpgsqlParameter<T>(this IEnumerable<T> enumerable, string parameterName)
{
    return new NpgsqlParameter
           {
               ParameterName = parameterName,
               Value = enumerable?.ToArray()
           };
}
```

with usages like this:

```
const string sql = "UPDATE bar SET foo = @0;"
database.Execute(sql, foo.ToArrayNpgsqlParameter("@p0"));
```

Unfortunately, this workaround only works when I am manually providing parameters. Certain NPoco methods like `Update` throw the same exception. As a result, I must write my `UPDATE` statements manually.

**Comment by nathan-alden** [comment]
I tried your suggestion from my other similar issue regarding enums. Unfortunately, the problem is that `GetParameterConverter`'s `sourceType` isn't an array, it's just `System.String`. It seems that something inside NPoco is "flattening" the array into a single value. Perhaps it's because my array only has a single element?

I would expect that if I pass an array value to an `IDatabaseQuery` method that NPoco would retain the fact that it's an array.

**Comment by schotime** [comment]
They do get flattened for `IN` clauses and since most languages don't actually support arrays being passed in, the most common scenario is this. 

To get around it, you can wrap the array in a class, and then create a generic mapper like in #313. Then sourcetype should be your wrapped class which you can unwrap and generate a parameter.

**Comment by nathan-alden** [comment]
I ended up writing a `Wrap` extension method that wraps the array in another array.

**Comment by kristina-alden-stenolab** [comment]
Unfortunately, this issue is probably going to prevent me from using NPoco. I cannot justify all the manual SQL I'm having to write; if I wanted to write all my SQL manually, I'd just use Npgsql directly. It would be very, very nice if NPoco exposed a configuration that simply didn't flatten arrays. It's trying to be too smart and it's hurting legitimate uses of types in one of its supported database engines.

**Comment by nathan-alden** [comment]
Unfortunately, this issue is probably going to prevent me from using NPoco. I cannot justify all the manual SQL I'm having to write; if I wanted to write all my SQL manually, I'd just use Npgsql directly. It would be very, very nice if NPoco exposed a configuration that simply didn't flatten arrays. It's trying to be too smart and it's hurting legitimate uses of types in one of its supported database engines.

**Comment by schotime** [comment]
You don't have to write manual sql. Just need to call your extension method on your arrays.

**Comment by nathan-alden** [comment]
Unfortunately, this is not true. There are several very useful methods in NPoco, such as Insert<T>, Update<T>, etc. that take a POCO object. Those methods read array properties and flatten them with no chance to call `Wrap` first. Wrapping the property is not an option because that would affect other uses of the POCO. The only option I have is writing manual SQL.

**Comment by NeilQ** [comment]
Not sure if this issue is still alive.
I've created a custom mapper to handle postgresql array type, along with json type, for your reference.

```csharp
public class DbJson
{
    public string Value { get; set; }
}

public class DbStringArray
{
    public List<string> Value;
}

 public class MyDbMapper : DefaultMapper
 {
        public override Func<object, object> GetToDbConverter(Type destType, MemberInfo sourceMemberInfo)
        {
            if (sourceMemberInfo.GetMemberInfoType() == typeof(string) && destType == typeof(DbJson))
            {
                return x => new DbJson { Value = (string)x };
            }
            if (sourceMemberInfo.GetMemberInfoType() == typeof(IList<string>) && destType == typeof(DbStringArray))
            {
                return x => new DbStringArray { Value = (List<string>)x };
            }

            return base.GetToDbConverter(destType, sourceMemberInfo);
        }

        public override Func<object, object> GetParameterConverter(DbCommand dbCommand, Type sourceType)
        {
            if (sourceType == typeof(DbJson))
            {
                return x => new NpgsqlParameter
                {
                    NpgsqlDbType = NpgsqlDbType.Json,
                    Value = ((DbJson)x).Value
                };
            }
            if (sourceType == typeof(DbStringArray))
            {
                return x => new NpgsqlParameter
                {
                    // ReSharper disable once BitwiseOperatorOnEnumWithoutFlags
                    NpgsqlDbType = NpgsqlDbType.Array | NpgsqlDbType.Text,
                    Value = ((DbStringArray)x).Value
                };
            }

            return base.GetParameterConverter(dbCommand, sourceType);
        }

        public override Func<object, object> GetFromDbConverter(Type destType, Type sourceType)
        {
           
            if (destType == typeof(IList<string>) && sourceType == typeof(Array))
            {
                return x =>
                {
                    var result = new List<string>((string[])x);
                    return result;
                };
            }

            return base.GetFromDbConverter(destType, sourceType);
        }
 }
```

And the poco 

```csharp
  [ColumnType(typeof(DbStringArray))]
  public IList<string> Labels{ get; set; }
```

It works fine with me.
