### ISSUE TITLE
Does V3 support mapping to internal or private properties with fluent mapping?

### ISSUE THREAD

**Issue by lctjohn** [schotime/NPoco#414]
1. Does mapping to internal or private properties still work in V3, as mentioned in issue #126?
2. If so, does it require attribute mapping?

I'm using fluent mapping and was not able to get NPoco to map to a private property with Query<T>().

POCO:

    public class PriceDefinition
    {
        private decimal Price { get; set; }

        public int Id { get; set; }
        public int ProductId { get; set; }
    }

Mapping:

    For<PriceDefinition>().PrimaryKey(x => x.Id)
        .TableName("PriceTable")
        .Columns(config =>
        {
            config.Column(c => c.Id).WithName("PriceId");
        });

Query:
   
    var activeFromPriceDefinitions = Database.Query<Price>().ToList();

Resulting `activeFromPriceDefinitions` will have the correct ProductId value, but Price won't.

If V3 still nominally supports this I'll try creating an actual minimal repro to rule out config errors in the codebase.

**Comment by schotime** [comment]
Yes. It still supports this.

**Comment by SemiNormal** [comment]
No, it doesn't seem to support this.

ReflectionUtil.cs only has `BindingFlags.Public` on the `GetFieldsAndProperties` method.
Also, in MemberAccessor.cs the call to `GetGetMethod` in [GetGetDelegate](https://github.com/schotime/NPoco/blob/2f41c21af8e8bfa13558b28b2cdbecd604d16655/src/NPoco/MemberAccessor.cs#L189) is only looking at public get accessors. 

Changing the binding flags in `GetFieldsAndProperties` to include `BindingFlags.NonPublic` and changing `GetGetMethod()` to `GetGetMethod(true)` fixes the issue, but now **all** private, protected, and internal properties are included (causing a whole bunch of other issues).

**Comment by theHammadi** [comment]
as @SemiNormal said mapping for Private Properties doesn't work properly for inserting or updating records.

here is an example:
i created a simple console application that fetches and updates for DB objects that uses the newest version of NPoco from Nuget 4.0.2 on .NETCORE 2.1.

    static void Main(string[] args)
            {

            using (IDatabase DB = new Database("server=.;database=NancyUser; Integrated Security=True;MultipleActiveResultSets=true", DatabaseType.SqlServer2012, System.Data.SqlClient.SqlClientFactory.Instance)) {


                List<Usermodel> users  = DB.Fetch<Usermodel>();

                foreach (Usermodel user in users) {
                    user.Username = "KARS";
                }
                
                DB.BeginTransaction();


                foreach (Usermodel user in users)
                {
                    DB.Save(user);
                }


                DB.CompleteTransaction();
            }
        }

Using this POCO:

    [PrimaryKey("GUID", AutoIncrement = false)]
    [TableName("[USERS]")]
    class Usermodel
    {
        public Guid GUID { get; set; }
        [Column("USERNAME")]
        public string Username { get; set; }
        [Column("PASSWORD")]
        private string Password { get; set; }
        [Column("LASTUPDATED")]
        internal DateTime lastUpdated { get; set; }


        public Usermodel() {
            Password = "555555555555";
        }
    }


when i try to read the data i get "555555555555" for the password and 1/1/0001 for the date:
![image](https://user-images.githubusercontent.com/16575222/69735072-12b7e280-10fe-11ea-96fd-465d24ae5205.png)


but when it writes to the DB i get nothing for the password, i do get a value for the datetime because i have set a default in the DB:
![image](https://user-images.githubusercontent.com/16575222/69735035-ff0c7c00-10fd-11ea-8328-a9858fab1c97.png)

is there an issue here or are we missing something?

A great use case for this in my opinion is to be able to set some variables in the class itself without exposing them to consuming classes such example is while sending data to frontend i wanted to avoid sending Last modified date or such information to the front end but i needed to keep them as public to make the mapping work so i had to create another class and map the data from the DB using class to the other class.

**Comment by schotime** [comment]
From v5 alpha-4
