### ISSUE TITLE
Async operations using TPM

### ISSUE THREAD

**Issue by enriko-riba** [schotime/NPoco#45]
Any chance we get Async versions based on IOCP for Fetch, Single, etc. ?
E.g for SQL Server flavor something in the line of BeginExecuteReader.

Like: T t = await db.FetchAsync<T>( sql );

**Comment by schotime** [comment]
Hey,
I have just add some async methods to NPoco 2.7.95-beta for .net 4.5
These include:
```
QueryAsync<T>(string sql, object[] args)
InsertAsync<T>(T Poco)
UpdateAsync<T>(T Poco)
No delete yet.
Query Provider contains ToEnumerableAsync() and many other async methods (first, single, count, any etc)
```

Its just a start, but it is reusing a lot of the code which is great.
Also created a NPoco.Async.NET4 which uses Microsoft.Bcl.Async to run async on .NET4.

Adam

**Comment by schotime** [comment]
All the async stuff is currently in the 2.8.* beta releases. Lots implemented now.

**Comment by qstarin** [comment]
I know this is a long closed issue, but I'm not sure if there's a better place to ask questions..

I'm quite confused by the async and Query api in NPoco. I have a complicated Sql object for a query that joins several tables and applies several conditions to ultimately select a single value. For performance reasons I do not want the query to select any extra columns or rows.

For non-async, I can simply use:

`var id = db.SingleOrDefault<int?>(BuildComplicatedSqlObj(arg1, arg2, arg3));`

I don't see a SingleOrDefaultAsync off of NPoco.Database. If I wanted to do that with a simpler query off one table and a where clause I found I could use:

`var result = await db.Query<MyPocoClass>().Where($"Column1=@0", arg1).SingleOrDefaultAsync();`

Is there any way to accomplish that with my existing Sql object or a way to accomplish not selecting extraneous columns and rows using SqlBuilder or the fluent API off of Query? I'd prefer not to use expressions and linq conversions again for performance reasons (and since I already have Sql objects written and tested), unless that's the only way.

If I pass the Sql to Query I have to await that and get an IEnumerable then SingleOrDefault off of that will it just pull the first row and not the rest?
