### ISSUE TITLE
Use specific database while selecting by FirstOrDefault

### ISSUE THREAD

**Issue by ErcinDedeoglu** [schotime/NPoco#489]
I'm trying this but 
var databaseSyncLog = dbContext.SingleOrDefault<object>("USE Database1 SELECT * FROM Table1 Order By ID desc");
**order by** not working while I'm using "order by".

Is there a good way to run this command?

**Comment by tbasallo** [comment]
Off the top of my head you can try any of the following (#4 may not work)

1. Execute("USE Datbase1") -- this should work
2. db.Connection.ChangeDatabase("Database1") -- this will work
3. db.SingleOrDefault("SELECT * FROM Database1.dbo.Table1...") -- this will work (and is the best because no additional calls(
4. db.SingleOrDefault("USE database1; SELECT...") --maybe? I added a semicolon..maybe??

**Comment by schotime** [comment]
Create a new `Database` object per database.
