### ISSUE TITLE
Value Object support ?

### ISSUE THREAD

**Issue by SyanRtuart** [schotime/NPoco#561]
Hi,

I'm wondering if this is supported. I've been playing around but had no success.

Say I have an entity 

`    [TableName("SORTED_ITEM")]
    public class SortedItem : Entity
    {
        [Column("ORDER_NUMBER")]
        public string OrderNumber { get; set; }

        public ProductInfo ProductInfo { get; set; }
    }`

My product info class is a value object

` public class ProductInfo : ValueObject
    {
        [Column("PRODUCT_CODE")]
        public string Product { get; }

        [Column("COLOUR_CODE")]
        public string Colour { get; }

        [Column("SIZE_CODE")]
        public string Size { get; }

        [Column("BARCODE")]
        public string Barcode { get; }

        public ProductInfo(string product, string colour, string size, string barcode)
        {
            Product = product;
            Colour = colour;
            Size = size;
            Barcode = barcode;
        }

        protected override IEnumerable<object> GetAtomicValues()
        {
            yield return Product;
            yield return Colour;
            yield return Size;
            yield return Barcode;
        }
    }`

This is done because i'm using ProductInfo else where and i would like to keep my classes clean.

I've attempted to put different attributes onto the ProductInfo property on the SortedItem class but no joy so far.

Thanks

**Comment by firedog** [comment]
Maybe it is the ComplexMapping attribute you're after? I use fluent mapping myself and there you can specify a prefix to be used for columns belonging to the nested object (your ProductInfo object in SortedItem) so that all columns belonging to the nested object will be named PREFIX__PropertyName. The value of PREFIX is specified when performing the complex mapping. See #569 for an example of how complex mapping is used.

Tip: Use three backticks followed by c# to format code as c# here on Github (i.e.  \`\`\` c#). Close the code block using three backticks (i.e.  \`\`\`). The code function in the markdown editor just uses one backtick which makes the code block hard to read!

e.g.

```c#
TableName("SORTED_ITEM")]
public class SortedItem : Entity
{
    [Column("ORDER_NUMBER")]
    public string OrderNumber { get; set; }

    public ProductInfo ProductInfo { get; set; }
}
```
